name = "ProjA"
uuid = "1dcbef7a-afba-11e9-3cc2-4bc32cf8aae1"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
ProjC = "36ba297c-afba-11e9-203a-29180f4b1717"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
